[package]
org = "gayaldassanayake"
name = "bankingservice"
version = "0.1.0"
distribution = "2201.9.1"
visibility = "private"
export = ["bankingservice", "bankingservice.customers"]
icon = "resources/icon.png"
authors = ["gayaldassanayake", "Jane Doe"]
keywords = ["online banking", "ecommerce", "secure"]
license = ["MIT"]
repository = "https://github.com/gayaldassanayake/bankingservice"

[build-options]
observabilityIncluded = true
